[theme]
base="light"
primaryColor="#fd9e53"          
backgroundColor="#e6edf3ff"       
secondaryBackgroundColor="#c6d7e4ff"  
textColor="#2C3E50" 
font = "sans serif" # Clean, modern font

[server]
runOnSave=false